//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Tizen
{
    namespace Base
    {
        namespace Collection
        {
        }
    }
    namespace Ui
    {
        namespace Controls
        {
        }
    }
    namespace App
    {
        public delegate UiApp UiAppInstanceFactory();

        /// <summary>
        /// This class is the base class of a %Tizen native UI application.
        /// </summary>
        public unsafe partial class UiApp : Tizen.App.App, IDisposable
        {
            [StructLayout(LayoutKind.Explicit, Size = 12)]
            public new struct Internal
            {
                /// <summary>
                /// This is the default constructor for this class.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("SymbolNotFound", CallingConvention = CallingConvention.ThisCall,
                    EntryPoint="??0UiApp@App@Tizen@@IAE@XZ")]
                public static extern global::System.IntPtr UiApp0(global::System.IntPtr instance);

                /// <summary>
                /// Gets the UI state of the UI application.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("SymbolNotFound", CallingConvention = CallingConvention.ThisCall,
                    EntryPoint="?GetAppUiState@UiApp@App@Tizen@@QBE?AW4AppUiState@23@XZ")]
                public static extern AppUiState GetAppUiState0(global::System.IntPtr instance);

                /// <summary>
                /// Called when a UI application moves to the foreground. User interaction is enabled when the UI application moves to the foreground. A UI application moves to the foreground when:
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("SymbolNotFound", CallingConvention = CallingConvention.ThisCall,
                    EntryPoint="?OnForeground@UiApp@App@Tizen@@UAEXXZ")]
                public static extern void OnForeground0(global::System.IntPtr instance);

                /// <summary>
                /// Called when another UI application moves to the top or a system pop-up is displayed. User interaction is disabled when the UI application is in the background. A UI application moves to the background when:
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("SymbolNotFound", CallingConvention = CallingConvention.ThisCall,
                    EntryPoint="?OnBackground@UiApp@App@Tizen@@UAEXXZ")]
                public static extern void OnBackground0(global::System.IntPtr instance);

                /// <summary>
                /// Gets the %UiApp instance's pointer.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("SymbolNotFound", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="?GetInstance@UiApp@App@Tizen@@SAPAV123@XZ")]
                public static extern global::System.IntPtr GetInstance0();
            }

            internal UiApp(UiApp.Internal* native)
                : this(new global::System.IntPtr(native))
            {
            }

            internal UiApp(UiApp.Internal native)
                : this(&native)
            {
            }

            internal UiApp(global::System.IntPtr native)
                : base(native)
            {
            }

            protected override void Dispose(bool disposing)
            {
                base.Dispose(disposing);
            }

            /// <summary>
            /// Gets the UI state of the UI application.
            /// </summary>
            public AppUiState GetAppUiState()
            {
                var ret = Internal.GetAppUiState0(_Instance);
                return ret;
            }

            /// <summary>
            /// Called when a UI application moves to the foreground. User interaction is enabled when the UI application moves to the foreground. A UI application moves to the foreground when:
            /// </summary>
            public void OnForeground()
            {
                Internal.OnForeground0(_Instance);
            }

            /// <summary>
            /// Called when another UI application moves to the top or a system pop-up is displayed. User interaction is disabled when the UI application is in the background. A UI application moves to the background when:
            /// </summary>
            public void OnBackground()
            {
                Internal.OnBackground0(_Instance);
            }

            /// <summary>
            /// Gets the %UiApp instance's pointer.
            /// </summary>
            public static UiApp GetInstance()
            {
                var ret = Internal.GetInstance0();
                return new Tizen.App.UiApp(ret);
            }
        }
    }
}
