//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Tizen
{
    namespace App
    {
        public unsafe partial class AppRegistry : Tizen.Base.Object, IDisposable
        {
            [StructLayout(LayoutKind.Explicit, Size = 8)]
            public new struct Internal
            {
                /// <summary>
                /// This default constructor is intentionally declared as
                /// private to implement the %Singleton semantic.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZN5Tizen3App11AppRegistryC2Ev")]
                public static extern global::System.IntPtr AppRegistry0(global::System.IntPtr instance);

                /// <summary>
                /// Adds a string value along with the specified key.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZN5Tizen3App11AppRegistry3AddERKNS_4Base6StringES5_")]
                public static extern uint Add0(global::System.IntPtr instance, global::System.IntPtr key, global::System.IntPtr value);

                /// <summary>
                /// Adds an integer value along with the specified key.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZN5Tizen3App11AppRegistry3AddERKNS_4Base6StringEi")]
                public static extern uint Add1(global::System.IntPtr instance, global::System.IntPtr key, int value);

                /// <summary>
                /// Adds a floating point value along with the specified
                /// key.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZN5Tizen3App11AppRegistry3AddERKNS_4Base6StringEd")]
                public static extern uint Add2(global::System.IntPtr instance, global::System.IntPtr key, double value);

                /// <summary>
                /// Sets a string value associated with the specified key.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZN5Tizen3App11AppRegistry3SetERKNS_4Base6StringES5_")]
                public static extern uint Set0(global::System.IntPtr instance, global::System.IntPtr key, global::System.IntPtr value);

                /// <summary>
                /// Sets an integer value associated with the specified
                /// key.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZN5Tizen3App11AppRegistry3SetERKNS_4Base6StringEi")]
                public static extern uint Set1(global::System.IntPtr instance, global::System.IntPtr key, int value);

                /// <summary>
                /// Sets a floating point value associated with the
                /// specified key.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZN5Tizen3App11AppRegistry3SetERKNS_4Base6StringEd")]
                public static extern uint Set2(global::System.IntPtr instance, global::System.IntPtr key, double value);

                /// <summary>
                /// Saves the values temporarily in the persistent storage.
                /// The %Save() method is invoked internally when the instance
                /// of this class is deleted.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZN5Tizen3App11AppRegistry4SaveEv")]
                public static extern uint Save0(global::System.IntPtr instance);

                /// <summary>
                /// Removes a preference associated with the specified key.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZN5Tizen3App11AppRegistry6RemoveERKNS_4Base6StringE")]
                public static extern uint Remove0(global::System.IntPtr instance, global::System.IntPtr key);

                /// <summary>
                /// Gets a string value associated with the specified key.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZNK5Tizen3App11AppRegistry3GetERKNS_4Base6StringERS3_")]
                public static extern uint Get0(global::System.IntPtr instance, global::System.IntPtr key, global::System.IntPtr value);

                /// <summary>
                /// Gets an integer value associated with the specified
                /// key.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZNK5Tizen3App11AppRegistry3GetERKNS_4Base6StringERi")]
                public static extern uint Get00(global::System.IntPtr instance, global::System.IntPtr key, global::System.IntPtr value);

                /// <summary>
                /// Gets a floating point value associated with the
                /// specified key.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZNK5Tizen3App11AppRegistry3GetERKNS_4Base6StringERd")]
                public static extern uint Get1(global::System.IntPtr instance, global::System.IntPtr key, global::System.IntPtr value);

                /// <summary>
                /// Gets the %AppRegistry instance pointer.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="_ZN5Tizen3App11AppRegistry11GetInstanceEv")]
                public static extern global::System.IntPtr GetInstance0();
            }

            internal AppRegistry(AppRegistry.Internal* native)
                : this(new global::System.IntPtr(native))
            {
            }

            internal AppRegistry(AppRegistry.Internal native)
                : this(&native)
            {
            }

            internal AppRegistry(global::System.IntPtr native)
                : base(native)
            {
            }

            protected override void Dispose(bool disposing)
            {
                base.Dispose(disposing);
            }

            /// <summary>
            /// Adds a string value along with the specified key.
            /// </summary>
            public uint Add(String key, String value)
            {
                var arg0 = key._Instance;
                var arg1 = value._Instance;
                var ret = Internal.Add0(_Instance, arg0, arg1);
                return ret;
            }

            /// <summary>
            /// Adds an integer value along with the specified key.
            /// </summary>
            public uint Add(String key, int value)
            {
                var arg0 = key._Instance;
                var ret = Internal.Add1(_Instance, arg0, value);
                return ret;
            }

            /// <summary>
            /// Adds a floating point value along with the specified key.
            /// </summary>
            public uint Add(String key, double value)
            {
                var arg0 = key._Instance;
                var ret = Internal.Add2(_Instance, arg0, value);
                return ret;
            }

            /// <summary>
            /// Sets a string value associated with the specified key.
            /// </summary>
            public uint Set(String key, String value)
            {
                var arg0 = key._Instance;
                var arg1 = value._Instance;
                var ret = Internal.Set0(_Instance, arg0, arg1);
                return ret;
            }

            /// <summary>
            /// Sets an integer value associated with the specified key.
            /// </summary>
            public uint Set(String key, int value)
            {
                var arg0 = key._Instance;
                var ret = Internal.Set1(_Instance, arg0, value);
                return ret;
            }

            /// <summary>
            /// Sets a floating point value associated with the specified
            /// key.
            /// </summary>
            public uint Set(String key, double value)
            {
                var arg0 = key._Instance;
                var ret = Internal.Set2(_Instance, arg0, value);
                return ret;
            }

            /// <summary>
            /// Saves the values temporarily in the persistent storage. The
            /// %Save() method is invoked internally when the instance of this
            /// class is deleted.
            /// </summary>
            public uint Save()
            {
                var ret = Internal.Save0(_Instance);
                return ret;
            }

            /// <summary>
            /// Removes a preference associated with the specified key.
            /// </summary>
            public uint Remove(String key)
            {
                var arg0 = key._Instance;
                var ret = Internal.Remove0(_Instance, arg0);
                return ret;
            }

            /// <summary>
            /// Gets a string value associated with the specified key.
            /// </summary>
            public uint Get(String key, String value)
            {
                var arg0 = key._Instance;
                var arg1 = value._Instance;
                var ret = Internal.Get0(_Instance, arg0, arg1);
                return ret;
            }

            /// <summary>
            /// Gets an integer value associated with the specified key.
            /// </summary>
            public uint Get0(String key, global::System.IntPtr value)
            {
                var arg0 = key._Instance;
                var arg1 = value;
                var ret = Internal.Get00(_Instance, arg0, arg1);
                return ret;
            }

            /// <summary>
            /// Gets a floating point value associated with the specified
            /// key.
            /// </summary>
            public uint Get(String key, global::System.IntPtr value)
            {
                var arg0 = key._Instance;
                var arg1 = value;
                var ret = Internal.Get1(_Instance, arg0, arg1);
                return ret;
            }

            /// <summary>
            /// Gets the %AppRegistry instance pointer.
            /// </summary>
            public static AppRegistry GetInstance()
            {
                var ret = Internal.GetInstance0();
                return new Tizen.App.AppRegistry(ret);
            }
        }
    }
}
