//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

public partial class TizenFBaseLog
{
    public struct Internal
    {
        [SuppressUnmanagedCodeSecurity]
        [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
            EntryPoint="AppLogInternal")]
        public static extern void AppLogInternal0(System.IntPtr pFunction, int lineNumber, System.IntPtr pFormat);

        [SuppressUnmanagedCodeSecurity]
        [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
            EntryPoint="AppLogDebugInternal")]
        public static extern void AppLogDebugInternal0(System.IntPtr pFunction, int lineNumber, System.IntPtr pFormat);

        [SuppressUnmanagedCodeSecurity]
        [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
            EntryPoint="AppLogExceptionInternal")]
        public static extern void AppLogExceptionInternal0(System.IntPtr pFunction, int lineNumber, System.IntPtr pFormat);

        [SuppressUnmanagedCodeSecurity]
        [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
            EntryPoint="AppassertInternal")]
        public static extern void AppassertInternal0(System.IntPtr pFunction, int lineNumber);

        [SuppressUnmanagedCodeSecurity]
        [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
            EntryPoint="AppassertfInternal")]
        public static extern void AppassertfInternal0(System.IntPtr expr, System.IntPtr pFunction, int lineNumber, System.IntPtr pFormat);

        [SuppressUnmanagedCodeSecurity]
        [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
            EntryPoint="AppLogTagInternal")]
        public static extern void AppLogTagInternal0(System.IntPtr pTag, System.IntPtr pFunction, int lineNumber, System.IntPtr pFormat);

        [SuppressUnmanagedCodeSecurity]
        [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
            EntryPoint="AppLogDebugTagInternal")]
        public static extern void AppLogDebugTagInternal0(System.IntPtr pTag, System.IntPtr pFunction, int lineNumber, System.IntPtr pFormat);

        [SuppressUnmanagedCodeSecurity]
        [DllImport("libosp-appfw.so.1.2.1", CallingConvention = CallingConvention.Cdecl,
            EntryPoint="AppLogExceptionTagInternal")]
        public static extern void AppLogExceptionTagInternal0(System.IntPtr pTag, System.IntPtr pFunction, int lineNumber, System.IntPtr pFormat);
    }

    public static void AppLogInternal(string pFunction, int lineNumber, string pFormat)
    {
        var arg0 = Marshal.StringToHGlobalAnsi(pFunction);
        var arg2 = Marshal.StringToHGlobalAnsi(pFormat);
        Internal.AppLogInternal0(arg0, lineNumber, arg2);
        Marshal.FreeHGlobal(arg0);
        Marshal.FreeHGlobal(arg2);
    }

    public static void AppLogDebugInternal(string pFunction, int lineNumber, string pFormat)
    {
        var arg0 = Marshal.StringToHGlobalAnsi(pFunction);
        var arg2 = Marshal.StringToHGlobalAnsi(pFormat);
        Internal.AppLogDebugInternal0(arg0, lineNumber, arg2);
        Marshal.FreeHGlobal(arg0);
        Marshal.FreeHGlobal(arg2);
    }

    public static void AppLogExceptionInternal(string pFunction, int lineNumber, string pFormat)
    {
        var arg0 = Marshal.StringToHGlobalAnsi(pFunction);
        var arg2 = Marshal.StringToHGlobalAnsi(pFormat);
        Internal.AppLogExceptionInternal0(arg0, lineNumber, arg2);
        Marshal.FreeHGlobal(arg0);
        Marshal.FreeHGlobal(arg2);
    }

    public static void AppassertInternal(string pFunction, int lineNumber)
    {
        var arg0 = Marshal.StringToHGlobalAnsi(pFunction);
        Internal.AppassertInternal0(arg0, lineNumber);
        Marshal.FreeHGlobal(arg0);
    }

    public static void AppassertfInternal(string expr, string pFunction, int lineNumber, string pFormat)
    {
        var arg0 = Marshal.StringToHGlobalAnsi(expr);
        var arg1 = Marshal.StringToHGlobalAnsi(pFunction);
        var arg3 = Marshal.StringToHGlobalAnsi(pFormat);
        Internal.AppassertfInternal0(arg0, arg1, lineNumber, arg3);
        Marshal.FreeHGlobal(arg0);
        Marshal.FreeHGlobal(arg1);
        Marshal.FreeHGlobal(arg3);
    }

    public static void AppLogTagInternal(string pTag, string pFunction, int lineNumber, string pFormat)
    {
        var arg0 = Marshal.StringToHGlobalAnsi(pTag);
        var arg1 = Marshal.StringToHGlobalAnsi(pFunction);
        var arg3 = Marshal.StringToHGlobalAnsi(pFormat);
        Internal.AppLogTagInternal0(arg0, arg1, lineNumber, arg3);
        Marshal.FreeHGlobal(arg0);
        Marshal.FreeHGlobal(arg1);
        Marshal.FreeHGlobal(arg3);
    }

    public static void AppLogDebugTagInternal(string pTag, string pFunction, int lineNumber, string pFormat)
    {
        var arg0 = Marshal.StringToHGlobalAnsi(pTag);
        var arg1 = Marshal.StringToHGlobalAnsi(pFunction);
        var arg3 = Marshal.StringToHGlobalAnsi(pFormat);
        Internal.AppLogDebugTagInternal0(arg0, arg1, lineNumber, arg3);
        Marshal.FreeHGlobal(arg0);
        Marshal.FreeHGlobal(arg1);
        Marshal.FreeHGlobal(arg3);
    }

    public static void AppLogExceptionTagInternal(string pTag, string pFunction, int lineNumber, string pFormat)
    {
        var arg0 = Marshal.StringToHGlobalAnsi(pTag);
        var arg1 = Marshal.StringToHGlobalAnsi(pFunction);
        var arg3 = Marshal.StringToHGlobalAnsi(pFormat);
        Internal.AppLogExceptionTagInternal0(arg0, arg1, lineNumber, arg3);
        Marshal.FreeHGlobal(arg0);
        Marshal.FreeHGlobal(arg1);
        Marshal.FreeHGlobal(arg3);
    }
}
