//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Tizen
{
    namespace System
    {
        public unsafe partial class Battery : IDisposable
        {
            [StructLayout(LayoutKind.Explicit, Size = 4)]
            public struct Internal
            {
                /// <summary>
                /// This is the default constructor for this class. This default constructor is intentionally declared as private so that only the platform can create an instance.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("SymbolNotFound", CallingConvention = CallingConvention.ThisCall,
                    EntryPoint="??0Battery@System@Tizen@@AAE@XZ")]
                public static extern System.IntPtr Battery0(System.IntPtr instance);

                /// <summary>
                /// Gets the current charge remaining in the battery as a percentage.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("SymbolNotFound", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="?GetCurrentLevelInPercentage@Battery@System@Tizen@@SAKAAH@Z")]
                public static extern uint GetCurrentLevelInPercentage0(System.IntPtr level);

                /// <summary>
                /// Gets the current charging level of the battery.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("SymbolNotFound", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="?GetCurrentLevel@Battery@System@Tizen@@SAKAAW4BatteryLevel@23@@Z")]
                public static extern uint GetCurrentLevel0(BatteryLevel level);

                /// <summary>
                /// Checks whether the battery is currently charging.
                /// </summary>
                [SuppressUnmanagedCodeSecurity]
                [DllImport("SymbolNotFound", CallingConvention = CallingConvention.Cdecl,
                    EntryPoint="?IsCharging@Battery@System@Tizen@@SAKAA_N@Z")]
                public static extern uint IsCharging0(System.IntPtr charging);
            }

            public System.IntPtr _Instance { get; protected set; }

            internal Battery(Battery.Internal* native)
                : this(new System.IntPtr(native))
            {
            }

            internal Battery(Battery.Internal native)
                : this(&native)
            {
            }

            internal Battery(System.IntPtr native)
            {
                _Instance = native;
            }

            public void Dispose()
            {
                Dispose(disposing: true);
                GC.SuppressFinalize(this);
            }

            protected virtual void Dispose(bool disposing)
            {
                Marshal.FreeHGlobal(_Instance);
            }

            /// <summary>
            /// Gets the current charge remaining in the battery as a percentage.
            /// </summary>
            public static uint GetCurrentLevelInPercentage(System.IntPtr level)
            {
                var arg0 = level;
                var ret = Internal.GetCurrentLevelInPercentage0(arg0);
                return ret;
            }

            /// <summary>
            /// Gets the current charging level of the battery.
            /// </summary>
            public static uint GetCurrentLevel(BatteryLevel level)
            {
                var arg0 = level;
                var ret = Internal.GetCurrentLevel0(arg0);
                return ret;
            }

            /// <summary>
            /// Checks whether the battery is currently charging.
            /// </summary>
            public static uint IsCharging(System.IntPtr charging)
            {
                var arg0 = charging;
                var ret = Internal.IsCharging0(arg0);
                return ret;
            }
        }
    }
}
